services:
  k3s-server:
    build:
      context: .
      dockerfile: Dockerfile.k3s-server
    container_name: k3s-server
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_TOKEN:-mysecrettoken}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    - WS_PORT=3000
    volumes:
#    - k3s-server:/var/lib/rancher/k3s
    - ./kubeconfig:/output
    ports:
    - "6443:6443"  # Kubernetes API Server
    - "80:80"      # Ingress controller HTTP
    - "443:443"    # Ingress controller HTTPS
    - "3000:3000"  # WebSocket Server
    networks:
      k3s-network:
        ipv4_address: 172.28.0.10

  k3s-agent-1:
    image: rancher/k3s:latest
    container_name: k3s-agent-1
    command: agent
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://k3s-server:6443
    - K3S_TOKEN=${K3S_TOKEN:-mysecrettoken}
    depends_on:
    - k3s-server
    networks:
      k3s-network:
        ipv4_address: 172.28.0.11

  k3s-agent-2:
    image: rancher/k3s:latest
    container_name: k3s-agent-2
    command: agent
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://k3s-server:6443
    - K3S_TOKEN=${K3S_TOKEN:-mysecrettoken}
    depends_on:
    - k3s-server
    networks:
      k3s-network:
        ipv4_address: 172.28.0.12

volumes:
  k3s-server:
    driver: local

networks:
  k3s-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/16
